/* ══════════════════════════════════════════════════════════════════════════
   Crisis module — print-ready Arabic-RTL reports (§24)
   Uses the browser's own print engine (a styled pop-up window) so Arabic
   shaping, bidi and page direction are always correct. Literal hex colours
   only — CSS custom properties do not resolve inside a fresh window.
   ════════════════════════════════════════════════════════════════════════ */
import {
  L, findById, fmtDate, fmtDateTime, riskScore, riskBand,
  INCIDENT_STATUSES, CRISIS_LEVELS, SEVERITIES, INCIDENT_CATEGORIES, INCIDENT_KINDS,
  LOCATIONS, ORG_UNITS, JOB_TITLES, IMPACT_DIMS, BIA_HORIZONS, BIA_LEVELS, biaPriority,
  PRIORITIES, ACTION_STATUSES, SERVICE_STATUS, READINESS, KPIS, attainment, kpiStatusOf,
  EXERCISE_TYPES, CONTACT_CATEGORIES,
} from './crisisData'

const esc = (s) => String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))

/* core: open a styled RTL/LTR window and print `body` under a branded header */
export function openPrintDoc({ title, subtitle, body, lang = 'ar', locale = 'ar' }) {
  const w = window.open('', '_blank', 'width=980,height=1000')
  if (!w) { alert('Please allow pop-ups to print reports.'); return }
  const rtl = lang === 'ar'
  const logo = `${window.location.origin}/fmac-ops-logo.png`
  w.document.write(`<!doctype html><html dir="${rtl ? 'rtl' : 'ltr'}" lang="${lang}"><head>
    <meta charset="utf-8"><title>${esc(title)}</title>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">
    <style>
      *{box-sizing:border-box}
      body{font-family:${rtl ? "'Cairo'," : ''}'Segoe UI',Tahoma,sans-serif;color:#14151a;margin:32px 40px;font-size:12px;line-height:1.55}
      .brand{display:flex;align-items:center;gap:14px;border-bottom:3px solid #b91c1c;padding-bottom:14px;margin-bottom:8px}
      .brand img{height:52px;width:auto}
      .brand-txt h1{font-size:19px;margin:0;color:#111}
      .brand-txt .sub{color:#6b7280;font-size:11.5px;margin-top:3px}
      .doc-title{font-size:16px;font-weight:800;margin:20px 0 2px}
      .doc-sub{color:#6b7280;font-size:11.5px;margin-bottom:14px}
      h2{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.07em;color:#b91c1c;margin:22px 0 8px;border-bottom:1px solid #eee;padding-bottom:4px}
      table{width:100%;border-collapse:collapse;margin:6px 0 14px}
      th{background:#f8fafc;text-align:${rtl ? 'right' : 'left'};font-size:9.5px;font-weight:700;color:#475569;padding:7px 6px;border-bottom:2px solid #e2e8f0;text-transform:uppercase;letter-spacing:.03em}
      td{padding:6px;border-bottom:1px solid #eef1f4;vertical-align:top}
      .pill{display:inline-block;padding:1px 8px;border-radius:99px;font-size:9.5px;font-weight:700;color:#fff}
      .kv{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px;margin:8px 0 14px}
      .kv .k{font-size:10px;color:#94a3b8;font-weight:700;text-transform:uppercase}
      .kv .v{font-size:12px;color:#14151a;margin-top:1px}
      .kv .cell{border-bottom:1px dotted #e5e7eb;padding-bottom:6px}
      .full{grid-column:1/-1}
      .num{white-space:nowrap;font-weight:600}
      .muted{color:#94a3b8}
      .heat{border-collapse:collapse}
      .heat td{width:52px;height:34px;text-align:center;color:#fff;font-weight:700;border:2px solid #fff}
      .foot{margin-top:26px;border-top:1px solid #eee;padding-top:10px;color:#9aa2ad;font-size:10px}
      @media print{body{margin:14px 18px}h2{page-break-after:avoid}tr{page-break-inside:avoid}}
    </style></head><body>
    <div class="brand"><img src="${logo}" alt="FMAC" onerror="this.style.display='none'"/>
      <div class="brand-txt"><h1>${rtl ? 'إدارة الأزمات والطوارئ' : 'Crisis & Emergency Management'}</h1>
      <div class="sub">${rtl ? 'نادي الفجيرة للفنون القتالية · إطار استمرارية الأعمال 2026–2028' : 'Fujairah Martial Arts Club · Business Continuity 2026–2028'}</div></div>
    </div>
    <div class="doc-title">${esc(title)}</div>
    <div class="doc-sub">${esc(subtitle || '')} · ${new Date().toLocaleDateString(locale)}</div>
    ${body}
    <div class="foot">${rtl
      ? 'أُنشئ عبر منظومة عمليات النادي — البيانات محسوبة لحظة الطباعة. وثيقة داخلية.'
      : 'Generated by the FMAC Operations Suite — figures computed at print time. Internal document.'} · ${new Date().toLocaleString(locale)}</div>
    </body></html>`)
  w.document.close(); w.focus()
  setTimeout(() => w.print(), 500)
}

const pill = (meta, lang) => meta ? `<span class="pill" style="background:${meta.hex || TONE[meta.tone] || '#64748b'}">${esc(L(meta, lang))}</span>` : '—'
const TONE = { good: '#16a34a', info: '#2563eb', warn: '#d97706', crit: '#dc2626', neutral: '#64748b' }

const kvCell = (k, v) => `<div class="cell"><div class="k">${esc(k)}</div><div class="v">${v == null || v === '' ? '—' : esc(v)}</div></div>`

/* ─────────────────────── incident report ─────────────────────── */
export function printIncidentReport({ incident: i, decisions = [], actions = [], services = [], lang, locale, t }) {
  const svcName = (id) => { const s = services.find(x => x.id === id); return s ? (lang === 'ar' ? s.name_ar : s.name_en) : id }
  const decRows = decisions.filter(d => d.incidentId === i.id)
  const actRows = actions.filter(a => a.incidentId === i.id)
  const body = `
    <div class="kv">
      ${kvCell(t('Incident no.', 'رقم الحادث'), i.number)}
      ${kvCell(t('Kind', 'النوع'), L(findById(INCIDENT_KINDS, i.kind || 'real'), lang))}
      ${kvCell(t('Category', 'الفئة'), L(findById(INCIDENT_CATEGORIES, i.category), lang))}
      ${kvCell(t('Level', 'المستوى'), L(findById(CRISIS_LEVELS, i.level), lang))}
      ${kvCell(t('Severity', 'الخطورة'), L(findById(SEVERITIES, i.severity), lang))}
      ${kvCell(t('Status', 'الحالة'), L(findById(INCIDENT_STATUSES, i.status), lang))}
      ${kvCell(t('Location', 'الموقع'), (i.locations || []).map(l => L(findById(LOCATIONS, l), lang)).join('، '))}
      ${kvCell(t('Unit', 'الوحدة'), L(findById(ORG_UNITS, i.unit), lang))}
      ${kvCell(t('Commander', 'قائد الحدث'), L(findById(JOB_TITLES, i.commander), lang))}
      ${kvCell(t('Reported', 'وقت الإبلاغ'), fmtDateTime(i.reportedAt || i.createdAt, locale))}
      <div class="cell full"><div class="k">${esc(t('Title', 'العنوان'))}</div><div class="v">${esc(lang === 'ar' ? (i.title_ar || i.title_en) : (i.title_en || i.title_ar))}</div></div>
      <div class="cell full"><div class="k">${esc(t('Description', 'الوصف'))}</div><div class="v">${esc(i.description)}</div></div>
      <div class="cell full"><div class="k">${esc(t('Affected services', 'الخدمات المتأثرة'))}</div><div class="v">${esc((i.affectedServices || []).map(svcName).join('، '))}</div></div>
    </div>
    <h2>${esc(t('Impact assessment', 'تقييم الأثر'))}</h2>
    <div class="kv">
      ${IMPACT_DIMS.map(d => kvCell(L(d, lang), i[`impact_${d.id}`])).join('')}
    </div>
    <h2>${esc(t('Decisions', 'القرارات'))} (${decRows.length})</h2>
    ${decRows.length ? `<table><thead><tr><th>#</th><th>${esc(t('Decision', 'القرار'))}</th><th>${esc(t('Maker', 'متخذ القرار'))}</th><th>${esc(t('Time', 'الوقت'))}</th></tr></thead><tbody>
      ${decRows.map(d => `<tr><td class="num">${esc(d.number)}</td><td>${esc(d.text)}</td><td>${esc(L(findById(JOB_TITLES, d.maker), lang))}</td><td>${esc(fmtDateTime(d.createdAt, locale))}</td></tr>`).join('')}
    </tbody></table>` : `<p class="muted">${esc(t('None recorded.', 'لا يوجد.'))}</p>`}
    <h2>${esc(t('Actions', 'الإجراءات'))} (${actRows.length})</h2>
    ${actRows.length ? `<table><thead><tr><th>${esc(t('Action', 'الإجراء'))}</th><th>${esc(t('Priority', 'الأولوية'))}</th><th>${esc(t('Status', 'الحالة'))}</th><th>${esc(t('Due', 'الاستحقاق'))}</th></tr></thead><tbody>
      ${actRows.map(a => `<tr><td>${esc(lang === 'ar' ? (a.description_ar || a.description_en) : (a.description_en || a.description_ar))}</td><td>${pill(findById(PRIORITIES, a.priority), lang)}</td><td>${pill(findById(ACTION_STATUSES, a.status), lang)}</td><td>${esc(a.dueDate || '—')}</td></tr>`).join('')}
    </tbody></table>` : `<p class="muted">${esc(t('None recorded.', 'لا يوجد.'))}</p>`}
    ${i.status === 'closed' ? `<h2>${esc(t('Closure', 'الإغلاق'))}</h2><div class="kv">
      ${kvCell(t('Root cause', 'السبب الجذري'), i.rootCause)}
      ${kvCell(t('Lessons learned', 'الدروس المستفادة'), i.lessons)}
      <div class="cell full">${kvCell(t('Closure summary', 'ملخص الإغلاق'), i.closureSummary)}</div>
    </div>` : ''}`
  openPrintDoc({ title: t('Incident Report', 'تقرير حادث') + ` · ${i.number}`, subtitle: lang === 'ar' ? i.title_ar : i.title_en, body, lang, locale })
}

/* ─────────────────────── BIA report ─────────────────────── */
export function printBiaReport({ service, bia, lang, locale, t }) {
  const grid = bia?.grid || {}
  const pr = bia?.override ? { en: bia.override, ar: bia.override, tone: 'info' } : biaPriority(grid)
  const matrix = `<table class="heat"><thead><tr><th>${esc(t('Impact / Time', 'الأثر / الوقت'))}</th>${BIA_HORIZONS.map(h => `<th>${esc(L(h, lang))}</th>`).join('')}</tr></thead><tbody>
    ${IMPACT_DIMS.map(d => `<tr><th>${esc(L(d, lang))}</th>${BIA_HORIZONS.map(h => { const v = grid?.[d.id]?.[h.id] || 0; const lv = findById(BIA_LEVELS, v); return `<td style="background:${lv?.hex || '#e2e8f0'};color:#14151a">${v}</td>` }).join('')}</tr>`).join('')}
  </tbody></table>`
  const body = `
    <div class="kv">
      ${kvCell(t('Service', 'الخدمة'), lang === 'ar' ? (service.name_ar || service.name_en) : service.name_en)}
      ${kvCell(t('Unit', 'الوحدة'), L(findById(ORG_UNITS, service.unit), lang))}
      ${kvCell(t('Recovery priority', 'أولوية التعافي'), L(pr, lang))}
      ${kvCell(t('MTPD', 'أقصى انقطاع'), bia?.mtpd)}
      ${kvCell(t('RTO', 'زمن التعافي'), bia?.rto)}
      ${kvCell(t('RPO', 'نقطة التعافي'), bia?.rpo)}
      ${kvCell(t('Min. operating level', 'الحد الأدنى للتشغيل'), bia?.minLevel)}
    </div>
    <h2>${esc(t('Impact over time', 'الأثر عبر الزمن'))}</h2>
    ${matrix}
    <p class="muted">${esc(t('0 = none · 4 = severe', '0 = لا يوجد · 4 = حرج'))}</p>
    <h2>${esc(t('Continuity', 'الاستمرارية'))}</h2>
    <div class="kv">
      <div class="cell full">${kvCell(t('Dependencies', 'الاعتماديات'), bia?.dependencies)}</div>
      <div class="cell full">${kvCell(t('Resources required', 'الموارد المطلوبة'), bia?.resources)}</div>
      <div class="cell full">${kvCell(t('Recovery strategy', 'استراتيجية التعافي'), bia?.recoveryStrategy)}</div>
    </div>`
  openPrintDoc({ title: t('Business Impact Analysis', 'تحليل أثر الأعمال'), subtitle: lang === 'ar' ? service.name_ar : service.name_en, body, lang, locale })
}

/* ─────────────────────── risk register ─────────────────────── */
export function printRiskRegister({ risks, lang, locale, t }) {
  const rows = risks.map(r => {
    const s = riskScore(r.probability, r.impact), b = riskBand(s)
    return `<tr><td>${esc(lang === 'ar' ? (r.title_ar || r.title_en) : r.title_en)}</td><td>${esc(L(findById(INCIDENT_CATEGORIES, r.category), lang))}</td><td class="num">${r.probability || '—'}</td><td class="num">${r.impact || '—'}</td><td class="num">${s || '—'}</td><td>${pill(b, lang)}</td><td>${esc(L(findById(JOB_TITLES, r.owner), lang))}</td></tr>`
  }).join('')
  const body = `<table><thead><tr><th>${esc(t('Risk', 'المخاطرة'))}</th><th>${esc(t('Category', 'الفئة'))}</th><th>P</th><th>I</th><th>${esc(t('Score', 'الدرجة'))}</th><th>${esc(t('Level', 'المستوى'))}</th><th>${esc(t('Owner', 'المالك'))}</th></tr></thead><tbody>${rows || `<tr><td colspan="7" class="muted">${esc(t('No risks.', 'لا مخاطر.'))}</td></tr>`}</tbody></table>`
  openPrintDoc({ title: t('Critical Risk Register', 'سجل المخاطر الحرجة'), subtitle: `${risks.length} ${t('risks', 'مخاطرة')}`, body, lang, locale })
}

/* ─────────────────────── services register ─────────────────────── */
export function printServicesRegister({ services, lang, locale, t }) {
  const rows = services.map(s => `<tr><td>${esc(lang === 'ar' ? (s.name_ar || s.name_en) : s.name_en)}</td><td>${esc(L(findById(ORG_UNITS, s.unit), lang))}</td><td class="num">${esc(s.rto || '—')}</td><td class="num">${esc(s.mtpd || '—')}</td><td>${pill(findById(PRIORITIES, s.priority), lang)}</td><td>${pill(findById(SERVICE_STATUS, s.status), lang)}</td><td>${pill(findById(READINESS, s.readiness), lang)}</td></tr>`).join('')
  const body = `<table><thead><tr><th>${esc(t('Service', 'الخدمة'))}</th><th>${esc(t('Unit', 'الوحدة'))}</th><th>RTO</th><th>MTPD</th><th>${esc(t('Priority', 'الأولوية'))}</th><th>${esc(t('Status', 'الحالة'))}</th><th>${esc(t('Readiness', 'الجاهزية'))}</th></tr></thead><tbody>${rows || `<tr><td colspan="7" class="muted">—</td></tr>`}</tbody></table>`
  openPrintDoc({ title: t('Critical Services Register', 'سجل الخدمات الحيوية'), subtitle: `${services.length} ${t('services', 'خدمة')}`, body, lang, locale })
}

/* ─────────────────────── KPI report ─────────────────────── */
/* targetsOverride: optional { [kpiId]: { [year]: value } } from
   crisis_settings/kpi_targets, so the printed report matches the admin-adjusted
   targets shown on-screen rather than the hard-coded catalog defaults. */
export function printKpiReport({ kpis, year, lang, locale, t, targetsOverride }) {
  const rows = KPIS.map(k => {
    const ov = targetsOverride?.[k.id]?.[year]
    const v = kpis[k.id]?.value, tgt = (ov ?? k.targets[year])
    const att = attainment(k, v, tgt), st = kpiStatusOf(att)
    const unit = k.ut === '%' ? '%' : k.ut === 'h' ? (lang === 'ar' ? ' س' : 'h') : ''
    return `<tr><td>${esc(L(k, lang))}</td><td class="num">${tgt}${unit}</td><td class="num">${v == null ? '—' : v + unit}</td><td class="num">${att == null ? '—' : Math.round(att) + '%'}</td><td>${pill(st, lang)}</td></tr>`
  }).join('')
  const body = `<table><thead><tr><th>${esc(t('Indicator', 'المؤشر'))}</th><th>${esc(t('Target', 'المستهدف'))} ${year}</th><th>${esc(t('Actual', 'الفعلي'))}</th><th>${esc(t('Attainment', 'الإنجاز'))}</th><th>${esc(t('Status', 'الحالة'))}</th></tr></thead><tbody>${rows}</tbody></table>
    <p class="muted">${esc(t('All values auto-calculated from live records. Never negative.', 'جميع القيم محسوبة تلقائياً من السجلات الحية ولا تكون سالبة.'))}</p>`
  openPrintDoc({ title: t('Crisis KPI Report', 'تقرير مؤشرات الأداء'), subtitle: `${t('Target year', 'سنة الهدف')} ${year}`, body, lang, locale })
}

/* ─────────────────────── executive summary ─────────────────────── */
export function printExecutiveSummary({ data, kpis, year, lang, locale, t }) {
  const { incidents = [], risks = [], services = [], corrective = [], exercises = [] } = data
  const active = incidents.filter(i => ['activated', 'responding', 'contained', 'recovering'].includes(i.status)).length
  const highR = risks.filter(r => ['high', 'crit'].includes(riskBand(riskScore(r.probability, r.impact)).id)).length
  const krow = (id) => { const k = findById(KPIS, id); const v = kpis[id]?.value; const unit = k.ut === '%' ? '%' : k.ut === 'h' ? (lang === 'ar' ? ' س' : 'h') : ''; return kvCell(L(k, lang), v == null ? '—' : v + unit) }
  const body = `
    <h2>${esc(t('Situation at a glance', 'الوضع باختصار'))}</h2>
    <div class="kv">
      ${kvCell(t('Active incidents', 'الحوادث النشطة'), active)}
      ${kvCell(t('Total incidents', 'إجمالي الحوادث'), incidents.length)}
      ${kvCell(t('Critical & high risks', 'مخاطر حرجة وعالية'), highR)}
      ${kvCell(t('Critical services', 'الخدمات الحيوية'), services.length)}
      ${kvCell(t('Open corrective actions', 'إجراءات تصحيحية مفتوحة'), corrective.filter(c => !['done', 'verified', 'cancelled'].includes(c.status)).length)}
      ${kvCell(t('Exercises recorded', 'التمارين المسجلة'), exercises.length)}
    </div>
    <h2>${esc(t('Readiness indicators', 'مؤشرات الجاهزية'))} · ${year}</h2>
    <div class="kv">
      ${krow('services_planned')}${krow('plans_tested')}${krow('recovery_success')}
      ${krow('avg_response')}${krow('avg_recovery')}${krow('rto_met')}
      ${krow('capa_ontime')}${krow('contacts_updated')}${krow('backup_ready')}
    </div>`
  openPrintDoc({ title: t('Executive Crisis Summary', 'الملخص التنفيذي للأزمات'), subtitle: t('Operations Department', 'إدارة العمليات'), body, lang, locale })
}

/* ─────────────────────── generic register export ─────────────────────── */
export function printExercisesReport({ exercises, lang, locale, t }) {
  const rows = exercises.map(e => `<tr><td>${esc(lang === 'ar' ? (e.title_ar || e.title_en) : e.title_en)}</td><td>${esc(L(findById(EXERCISE_TYPES, e.type), lang))}</td><td>${esc(fmtDate(e.date, locale))}</td><td>${esc(e.result || '—')}</td></tr>`).join('')
  const body = `<table><thead><tr><th>${esc(t('Exercise', 'التمرين'))}</th><th>${esc(t('Type', 'النوع'))}</th><th>${esc(t('Date', 'التاريخ'))}</th><th>${esc(t('Result', 'النتيجة'))}</th></tr></thead><tbody>${rows || `<tr><td colspan="4" class="muted">—</td></tr>`}</tbody></table>`
  openPrintDoc({ title: t('Exercises & Tests Report', 'تقرير التمارين والاختبارات'), subtitle: `${exercises.length}`, body, lang, locale })
}
export function printCorrectiveReport({ corrective, lang, locale, t }) {
  const rows = corrective.map(c => `<tr><td>${esc(c.action)}</td><td>${esc(L(findById(JOB_TITLES, c.owner), lang))}</td><td>${esc(c.dueDate || '—')}</td><td>${pill(findById(ACTION_STATUSES, c.status), lang)}</td></tr>`).join('')
  const body = `<table><thead><tr><th>${esc(t('Action', 'الإجراء'))}</th><th>${esc(t('Owner', 'المسؤول'))}</th><th>${esc(t('Due', 'الاستحقاق'))}</th><th>${esc(t('Status', 'الحالة'))}</th></tr></thead><tbody>${rows || `<tr><td colspan="4" class="muted">—</td></tr>`}</tbody></table>`
  openPrintDoc({ title: t('Corrective Actions Report', 'تقرير الإجراءات التصحيحية'), subtitle: `${corrective.length}`, body, lang, locale })
}
export function printContactsReport({ contacts, lang, locale, t }) {
  const rows = contacts.map(c => `<tr><td>${esc(c.name)}</td><td>${esc(L(findById(CONTACT_CATEGORIES, c.category), lang))}</td><td>${esc(c.org || '—')}</td><td dir="ltr">${esc(c.phone || '—')}</td></tr>`).join('')
  const body = `<table><thead><tr><th>${esc(t('Name', 'الاسم'))}</th><th>${esc(t('Category', 'الفئة'))}</th><th>${esc(t('Organization', 'الجهة'))}</th><th>${esc(t('Phone', 'الهاتف'))}</th></tr></thead><tbody>${rows || `<tr><td colspan="4" class="muted">—</td></tr>`}</tbody></table>`
  openPrintDoc({ title: t('Crisis Contact Directory', 'دليل جهات اتصال الأزمات'), subtitle: `${contacts.length}`, body, lang, locale })
}
